// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AddProductReader is a Reader for the AddProduct structure.
type AddProductReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddProductReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewAddProductCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddProductCreated creates a AddProductCreated with default headers values
func NewAddProductCreated() *AddProductCreated {
	return &AddProductCreated{}
}

/*
AddProductCreated describes a response with status code 201, with default header values.

No content is returned by this API endpoint
*/
type AddProductCreated struct {
}

// IsSuccess returns true when this add product created response has a 2xx status code
func (o *AddProductCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this add product created response has a 3xx status code
func (o *AddProductCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add product created response has a 4xx status code
func (o *AddProductCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this add product created response has a 5xx status code
func (o *AddProductCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this add product created response a status code equal to that given
func (o *AddProductCreated) IsCode(code int) bool {
	return code == 201
}

func (o *AddProductCreated) Error() string {
	return fmt.Sprintf("[POST /products][%d] addProductCreated ", 201)
}

func (o *AddProductCreated) String() string {
	return fmt.Sprintf("[POST /products][%d] addProductCreated ", 201)
}

func (o *AddProductCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
