basePath: /api/v1
definitions:
  main.album:
    properties:
      artist:
        type: string
      id:
        type: string
      price:
        type: number
      title:
        type: string
    type: object
host: localhost:5000
info:
  contact:
    email: abc@xyz.com
    name: API Support
  description: Swagger API for Golang Project Web service.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Example Swagger API
  version: "1.0"
paths:
  /albums:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.album'
            type: array
      summary: Retrieves list of album
    post:
      consumes:
      - application/json
      parameters:
      - description: New Album
        in: body
        name: album
        required: true
        schema:
          $ref: '#/definitions/main.album'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.album'
      summary: Creates album for the specified request
  /albums/{id}:
    get:
      parameters:
      - description: Album ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.album'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Retrieves album based on given ID
swagger: "2.0"
